using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using Liminal.SDK.VR;
using Liminal.SDK.VR.Input;
using System;

public class PewPewGunController : MonoBehaviour
{
    public float directDamage = 10f;                // Damage per shot
    public float cooldown = 0.2f;            // Time between shots
    public float heatPerShot = 10f;           // Amount of heat generated per shot
    public float overheatThreshold = 100f;   // Overheat threshold
    public float heatCooldownRate = 20f;     // Rate at which the gun cools down when overheated
    public float heatCooldownRateNormal = 5f; // Rate at which the gun cools down when not overheated
    public float maxRange; //how far the laser is rednered if nothing is hit 
    public float currentHeat = 0f;  // Current heat level

    private bool isOverheated = false;
    private AudioSource audioSource;

    public LineRenderer laserLine;
    public Transform gunBarrelEnd;


    private void Start()
    {
        audioSource = GetComponent<AudioSource>();

    }

    private void Update()
    {
        if (isOverheated)             // If the gun is overheated, start cooling down
        {
            currentHeat -= heatCooldownRate * Time.deltaTime;
        }
        else
        {
            currentHeat -= heatCooldownRateNormal * Time.deltaTime;
        }

        currentHeat = Mathf.Clamp(currentHeat, 0f, overheatThreshold);

        // Check if the gun is no longer overheated
        if (isOverheated && currentHeat < overheatThreshold)
        {
            isOverheated = false;
        }


        var primaryInput = VRDevice.Device.PrimaryInputDevice;
    
        if (!isOverheated && primaryInput.GetButtonDown(VRButton.One) || Input.GetMouseButtonDown(0)) //Checking if gun can fire when you initially press down
        {
            PewPew();
        }

    }

    private void PewPew()
    {

        // Add heat generated by the shot
        currentHeat += heatPerShot;

        // Fire sound
        audioSource.Play();

        if (Physics.Raycast(gunBarrelEnd.position, gunBarrelEnd.forward, out RaycastHit hit))
        {
            // Draw the laser line in the direction the gun was pointing.
            laserLine.enabled = true;
            laserLine.SetPosition(0, gunBarrelEnd.position);
            laserLine.SetPosition(1, hit.point);

            //get the directly hit enemy
            EnemyHealth directEnemyHealth = hit.collider.GetComponent<EnemyHealth>();

            //Do damage to the the directly hit enemy (if there is one)
            if (directEnemyHealth != null)
            {
                directEnemyHealth.Damage(directDamage, DamageType.Gun);
            }


        }
        else
        {
            // Draw the laser line in the direction the gun was pointing.
            laserLine.enabled = true;
            laserLine.SetPosition(0, gunBarrelEnd.position);
            laserLine.SetPosition(1, gunBarrelEnd.position + gunBarrelEnd.forward * maxRange);

            

        }

        //Overheat gun (AKA isOverheated = true) if this shot pushed over threshold
        if (currentHeat + heatPerShot >= overheatThreshold)
        {
            isOverheated = true;
            StartCoroutine(CoolDown());
        }

        //Turn everything off
        Invoke("TurnOffLaser", 0.3f);
    }

    private IEnumerator CoolDown()
    {
        while (currentHeat > 0)
        {
            yield return new WaitForSeconds(1.0f);
            currentHeat -= heatCooldownRate;
        }

    }

    private void TurnOffLaser()
    {
        laserLine.enabled = false;
    }
}
